[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[s3tui]
source = "github"
github = "softberries/s3tui"
use_max_tag = true
prefix = "v"

["nob.h"]
source = "github"
github = "tsoding/nob.h"
use_max_tag = true
prefix = "v"

[python-hwdata]
source = "github"
github = "xsuchy/python-hwdata"
use_max_tag = true
prefix = "python-hwdata-"

[nodejs-ramadan-cli]
source = "npm"
npm = "ramadan-cli"

[python-nanoid]
source = "pypi"
pypi = "nanoid"

[python-cs50]
source = "github"
github = "cs50/python-cs50"
use_max_tag = true
prefix = "v"

[python-extra-platforms]
source = "github"
github = "kdeldycke/extra-platforms"
use_max_tag = true
prefix = "v"

[python-pyborgeous]
source = "pypi"
pypi = "pyborgeous"

[python-markovify]
source = "github"
github = "jsvine/markovify"
use_max_tag = true
prefix = "v"

[deadbranch]
source = "github"
github = "armgabrielyan/deadbranch"
use_max_tag = true
prefix = "v"

[nodejs-ripencli]
source = "npm"
npm = "ripencli"

[python-spdx-tools]
source = "github"
github = "spdx/tools-python"
prefix = "v"
